apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    DB_PASSWORD: AgAUqMiNLohnmZp30hSQim2dyIBisy4I1qA13p/94t21F3dCrXdmm6/LYQvJq2LEndJXYcwsdscGR9601CdzsgmFXfRySZ+/QxxqRfbGP73+VOhovbLnz9d4s604Y0bIHS3wNxn3DC0uhmuQ6sfsdcquZbx7V9ScUW7zpZfg7NlH9ujDh8Wg1to4JVUCHtUzlaqDOxdI+S5fQKjSHYhYdyBir419YzkBe8YmYMhjf0r6+Bstdut5J70ekOR3i0OSQSj3i9UHq80xRzBtvI7ecRSNvf550FgAT6kwz5A34HeBGbIMO0PmtEw1aN9VYpT76U/X1BG9p6yaVXU1G1WVlKQZGkH/qbP/BVHlh4nEheW4w+Xu+h3WOy613J2VRsX3YmsKmKh4GOo2vL7UvGtVVYJdWwved6UseMiB9uK4awSOn1DlpxuBGt2iyIszbCgOeYCvpcd68o4WpUiX9bJp1DEamGDy51d0PF6nWfcHHKCWqDTb4dT6LR1gvIq8V4qnO2LsqQZ9gbnD6lemmp2Zhx/OaSkTfulkgNfYKKM9nKXRrg+ZtAgqMhp7GXdr9HMD5I7F1/3TBXU2hSzjmEt9uN0HLE8PcdWZi7YtUpUvJh9PxNH3imY1Y0VKbATaV75NYxiQDbCGVRcQj3G8AMVn05h2qy0mFMKRE07joNw6J4wTc0VDcgkVEucvjoIaxP5efWkzej/Ac2cXKQ==
    DB_USER: AgCdUIrXC/VTXRW3MLWdR+fKCfQ2IfN64fudIkWxwJrXGYPyusHr/vbCkIQEPXZXjgA+CeyP2iGcbjmxU0lGU1vMKUNUhdG+ucWCv3Yq9yphLj3pNdPuJrJ/GTk4p0bvLFtfqON4OP5qnXSaP2vlc+JJ6SYdT8s7XQjfKSjFQWhA/eQaW7TU94QEvPebKQ/ROnxNP3o/l/AX+4M5Xhi4gf6I/CK00oyuOJFtRZuvcjabJ9LKMpW9QdOUqFMpj4GubjEwbddHVTIIud28BXyemTb7AgyUPy58JK3PuF7hp5OM5QJRGLUIXdUuRZTgr4CgVyBwGZPPrTIGQfDDUWTaDWoaXy456MGU5xqf6LqAOmLkt/GNLbxSNyovf+8UKkmornums3mXhSwJtp9dJuJ2d5Ysv4WcoR3zSqSoKPMo6BGofezVhvrz7OZHMcod5Cj9V7dVwFFtTVGy+JrFQ6VGLUMrE6o0dSc9g4xECIFuaXvKAEpgCC2FjUDdYaK4x5Qd9K/73r71nx/Tar62GZBclVF04Iip0GZkczs/zuXJkpgDQj7KDqihmcDHGbEYLLmmJfaVT2pf3DTlyKCh9KBTk4Rp4BdUZqxakductKszhifNdcoWvhgwM5/Qc4SfqjP5NCB4B3EhhJTfTTBZ6A/rRKTjYorHWjHw0Ud59cgeaeh+KysqCF29hxccIPUyryLAUrQjEtK/l1EmdQ==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: b2bi-prod
    type: Opaque

