apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-system-passphrase-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    SYSTEM_PASSPHRASE: AgDYx4UXtNJXI7bXPJgMmz3te3pQIKnuKO1CU8slusMURpvWVtTYHn+Vl17pj4e5JNwCrSzDqDSIR6JRLXlgwhj7YIOXdXMo6RUKvpaz1/kyQHupP0vQqIFZY9iMyPfwECfpsuwC2OHP94/wzu8Ttl5NNqyVEPUWYuLL6ZSWv5mYDzgQ5jhtxbymJfl0rm7hTo8WY6lq2oa0J5DRb7hmblPseN7iJHY5sOyNCOYRkKf38Tj8enlvmAsmPjGNM1p9bYT0cI0Da4NyqJ3tzDgctzhQtSIatd/QqpXshofL1O7T2c3+yLwqKPNQpvu0g9jIZuqWPMjmrop/LPhD5biQGOVtKgVhSQJ52eT2HTZuZITeuZn1B9C6w2r2T38cvP1pCOpR79BTjExxvCPVddYtrpv92TbYEUzEV8zVyuqcHOvFfkOjMpY5tni/HEvAFOT3NqKPyge6pr3COtwzzaxA/5w9ZP+pBkqaP82H0dtY+bf5PuwFOa6w1HsxuqOk5DAmKuD1ZaKhO9zcCeeO8hik6cOtzMKPGiaDeGPPvW6Rs0OtA0TVLZ/n4CUkGRs47q/n6HC+fqR/77DC2vRXn4NaMR2pT2Xb5R/kr/EB8jjYVI3N7uS/cFYRt9XgAWrkpzun11g0HJpvt2fFawBXYNZc313hXhF15UTNxLvgXfz/vG/wQk6F8N7tJvMcOtgjbu2dG5ryhTe56Jrw/A==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-system-passphrase-secret
      namespace: b2bi-prod
    type: Opaque

